<?php

namespace common\components;

class Formatter extends \yii\i18n\Formatter
{
    public function asCurrency($value, $currency = null, $options = [], $textOptions = [])
    {
        return parent::asCurrency($value / 100, $currency, $options, $textOptions); // TODO: Change the autogenerated stub
    }
}