<?php

namespace common\models;

use Yii;
use yii\behaviors\TimestampBehavior;

/**
 * This is the model class for table "call".
 *
 * @property int $id
 * @property string|null $call_id
 * @property int $line_id
 * @property int $tariff_id
 * @property string|null $source
 * @property string|null $destination
 * @property string|null $record_link
 * @property int|null $duration
 * @property int|null $billing_duration
 * @property int|null $status
 * @property string $direction
 * @property int $created_at
 * @property int $updated_at
 *
 * @property Line $line
 * @property CallTariff $tariff
 */
class Call extends \yii\db\ActiveRecord
{
    const string DIRECTION_IN = 'in';
    const string DIRECTION_OUT = 'out';

    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'call';
    }

    public function behaviors()
    {
        return [
            TimestampBehavior::class
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['call_id', 'source', 'destination', 'record_link', 'duration', 'billing_duration', 'status'], 'default', 'value' => null],
            [['line_id', 'tariff_id', 'duration', 'billing_duration', 'status', 'created_at', 'updated_at'], 'integer'],
            [['call_id', 'source', 'destination', 'record_link', 'direction'], 'string', 'max' => 255],
            [['call_id'], 'unique'],
            [['line_id'], 'exist', 'skipOnError' => true, 'targetClass' => Line::class, 'targetAttribute' => ['line_id' => 'id']],
            [['tariff_id'], 'exist', 'skipOnError' => true, 'targetClass' => CallTariff::class, 'targetAttribute' => ['tariff_id' => 'id']],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'call_id' => 'ID',
            'line_id' => 'Line',
            'tariff_id' => 'Tariff',
            'source' => 'Source',
            'destination' => 'Destination',
            'record_link' => 'Record',
            'duration' => 'Duration',
            'billing_duration' => 'Billing Duration',
            'status' => 'Status',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
        ];
    }

    /**
     * Gets query for [[Line]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getLine()
    {
        return $this->hasOne(Line::class, ['id' => 'line_id']);
    }

    /**
     * Gets query for [[Tariff]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getTariff()
    {
        return $this->hasOne(CallTariff::class, ['id' => 'tariff_id']);
    }

    public function beforeSave($insert)
    {
        if($this->isNewRecord && $this->tariff_id === null) {
            if($this?->line?->tariff?->default_call_tariff_id) {
                $this->tariff_id = $this?->line?->tariff?->default_call_tariff_id;
            } else if(env('DEFAULT_CALL_TARIFF_ID')) {
                $this->tariff_id = env('DEFAULT_CALL_TARIFF_ID');
            }
        }
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }

    public function getSum() : float
    {
        if($this->tariff) {
            if($this->direction === self::DIRECTION_OUT) {
                return round($this->tariff->price_out * ($this->billing_duration / 60), 2);
            }
            return round($this->tariff->price_in * ($this->billing_duration / 60), 2);
        }
        return 0;
    }

    public function getRecord() : string
    {
        $y = Yii::$app->formatter->asDate($this->created_at, 'php:Y');
        $m = Yii::$app->formatter->asDate($this->created_at, 'php:m');
        $d = Yii::$app->formatter->asDate($this->created_at, 'php:d');

        $src = "$y/$m/$d/$this->record_link";
        $audio = ' <audio controls>
  <source src="'.$src.'" type="audio/wav">
  <source src="horse.mp3" type="audio/mpeg">
  Your browser does not support the audio tag.
</audio>';

        return $audio;
    }
}
